[package]
name = "bella"
version = "0.1.0"
edition = "2021"
authors = ["Julian Górski"]



[dependencies]
bevy = { version = "0.15.0", features = ["dynamic_linking", "trace_tracy"] }
bevy-inspector-egui = { version = "0.28.0" }
bevy_egui = "0.31.1"

csv = "1.3.1"
rand = "0.8.5"
itertools = "0.13.0"
config = { version = "0.15.4", features = ["toml"] }
noise = { version = "0.9.0", features = ["images"] }
serde = { version = "1.0.217", features = ["derive"] }
rand_distr = "0.4.3"



[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
