[package]
name = "bella"
version = "0.1.0"
edition = "2021"
authors = ["Julian Górski"]

[dependencies]
bevy = { version = "0.14.0", features = ["dynamic_linking", "trace_tracy"] }
bevy_egui = "0.28.0"
config = { version = "0.14.0", features = ["toml"] }
hexx = "0.17.0"
itertools = "0.13.0"
noise = { version = "0.9.0", features = ["images"] }
plotters = "0.3.6"
rand = "0.8.5"
serde = { version = "1.0.200", features = ["derive"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
