[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C",
    # "link-arg=-fuse-ld=lld",
    "link-arg=-fuse-ld=/usr/bin/mold",
    # (Nightly) Make the current crate share its generic instantiations
    # "-Zshare-generics=y",
]

