development_time = 20
waiting_for_reproduction_time = 15
carnivores_to_herbivores_ratio = 0.5

[group_spawn_on_sand_chance]
type = "chance"
chance = 0.5

[group_size_dist]
type = "range"
min = 1
max = 10
