group_spawn_chance:
  type: "chance"
  chance: 0.2

group_size_dist:
  type: "range"
  min: 2
  max: 4

size_dist:
  type: "normal"
  mean: 2.0
  std: 1.0
  min: 1.0

diet_dist:
  type: "weightedchoice"
  choices: [0, 1, 2]
  weights: [0.4, 0.5, 0.1]

do_nothing_for_hours: 2
