group_spawn_chance:
  type: "chance"
  chance: 0.2

group_size_dist:
  type: "range"
  min: 2
  max: 4

size_dist:
  type: "normal"
  mean: 2.0
  std: 1.0
  min: 1.0

diet_dist:
  type: "weightedchoice"
  choices: [0, 1, 2]
  weights: [0.8, 0.1, 0.1]

max_health_gene_config:
  multiplier: 65.0
  offset: 10.0

speed_gene_config:
  multiplier: 0.9
  offset: 0.1

sight_range_gene_config:
  multiplier: 300.0
  offset: 0.0

action_range_gene_config:
  multiplier: 20.0
  offset: 0.0

attack_damage_gene_config:
  multiplier: 5.0
  offset: 0.0

energy_to_survive_per_mass_unit_gene_config:
  multiplier: 1.0
  offset: 0.2

do_nothing_for_hours: 2

reproduction_cooldown_gene_config:
  max_value: 24
  min_value: 24

maturity_age_gene_config:
  max_value: 24
  min_value: 24