creature_spawn_x = 2
creature_spawn_y = 1

plant_group_spawn_chance_grass = 0.2
plant_group_size_min = 4
plant_group_size_max = 20

map_radius = 20
hex_size = 50.0

biome_overlay_update_cooldown = 60.0
thermal_overlay_update_cooldown = 1.0