starting_hour: 0
sun_energy_output_per_tile: 1000.0
sun_energy_output_per_plant: 100.0
sun_day_energy_ratio: 1.0
sun_night_energy_ratio: 0.2

water_humidity: 1.0
humidity_spread_coefficient: 0.8