carcass_energy_decay = 0.1

# Update
[max_active_energy_dist]
mean = 2000.0
std = 200.0

# Startup
[starting_mass_dist]
mean = 3.0
std = 0.5
min = 1.0

# Update
[energy_per_mass_unit_dist]
mean = 9000.0
std = 1000.0
min = 1000.0

# Update
[energy_consumption_per_mass_unit_dist]
mean = 10.0
std = 1.0
min = 1.0