max_health_gene_config:
  multiplier: 200.0
  offset: 0.0

max_active_energy_gene_config:
  multiplier: 200.0
  offset: 0.0

energy_to_survive_per_mass_unit_gene_config:
  multiplier: 1.0
  offset: 0.3

reproduction_energy_cost_gene_config:
  multiplier: 500.0
  offset: 0.0

maturity_age_gene_config:
  max_value: 12
  min_value: 1

reproduction_cooldown_gene_config:
  max_value: 12
  min_value: 3


starting_mass_dist:
  type: 'normal'
  mean: 50.0
  std: 0.5
  min: 1.0

offspring_spawn_range: 30.0
max_energy_consumption_per_mass_unit: 9.0
carcass_mass_decay_percentage: 0.1
