max_health_gene_config:
  multiplier: 200.0
  offset: 0.0

max_active_energy_gene_config:
  multiplier: 1000.0
  offset: 0.0

reproduction_energy_cost_gene_config:
  multiplier: 200.0
  offset: 0.0

age_penalty_gene_config:
  multiplier: 0.8
  offset: 0.2


starting_age_dist:
  type: 'range'
  max: 48
  min: 1

starting_mass_dist:
  type: 'normal'
  mean: 10.0
  std: 0.5
  min: 1.0

offspring_spawn_range: 100.0
carcass_mass_decay_percentage: 0.1
