energy_production_from_solar_efficiency_gene_config:
  multiplier: 2.0 # for now let's make it not matter (gene will have phenotype of around 1.0)
  offset: 0.0

nutrient_consumption_gene_config:
  multiplier: 2.0 # for now let's make it not matter (gene will have phenotype of around 1.0)
  offset: 0.0

pollination_range_gene_config:
  multiplier: 5000.0
  offset: 0.0


group_spawn_on_grass_chance:
  type: 'chance'
  chance: 1.0

group_size_dist:
  type: 'range'
  min: 2
  max: 8

energy_to_survive_per_mass_unit_gene_config:
  multiplier: 5.0
  offset: 1.0