development_time = 5
waiting_for_reproduction_time = 5
reproduction_range = 10.0

# Startup
[group_spawn_on_grass_chance]
type = "chance"
chance = 0.2

# Startup
[group_size_dist]
type = "range"
min = 3
max = 10

# Update ?
[max_health_dist]
type = "normal"
mean = 75.0
std = 20.0
min = 10.0
max = 150.0

# Update
[energy_efficiency_production_from_solar_dist]
type = "normal"
mean = 0.5
std = 0.1
min = 0.0
max = 1.0